# Generated by Django 2.2.7 on 2019-12-20 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_read', models.CharField(max_length=20, verbose_name='Прочитаєте за')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('views', models.IntegerField(default=0, verbose_name='Кількість переглядів')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Короткий опис')),
                ('published', models.DateTimeField(auto_now=True, verbose_name='Дата публікації')),
                ('title_image', models.ImageField(blank=True, default='posts/default.png', upload_to='posts', verbose_name='Зображення')),
                ('publication', models.TextField(verbose_name='Текст публікації')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Програмування'), (2, 'Шкільна інформатика'), (3, 'Інформаційні технології'), (4, 'Scratch'), (5, 'Стаття')], default=5)),
            ],
        ),
        migrations.CreateModel(
            name='PostHashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials_system.Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials_system.HashTag')),
            ],
        ),
    ]
