# Generated by Django 2.2.7 on 2020-09-03 18:57

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
                ('tag_main', models.BooleanField(default=False)),
                ('tag_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials_system.HashTag')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_read', models.CharField(max_length=20, verbose_name='Прочитаєте за')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('views', models.IntegerField(default=0, verbose_name='Кількість переглядів')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Короткий опис')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('title_image', models.ImageField(blank=True, default='posts/default.png', upload_to='posts', verbose_name='Зображення')),
                ('publication', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст публікації')),
                ('favorite', models.ManyToManyField(blank=True, related_name='Обрані', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='Лайки', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст комментаря')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата написання коментаря')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials_system.Post', verbose_name='Пост до якого написан комментар')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials_system.Comments', verbose_name='Вiдповiдь на')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментара')),
            ],
        ),
        migrations.CreateModel(
            name='PostHashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials_system.Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials_system.HashTag')),
            ],
            options={
                'unique_together': {('post', 'tag')},
            },
        ),
    ]
