# Generated by Django 2.2.7 on 2019-12-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='static/post_images/'),
        ),
    ]
