# Generated by Django 2.2.7 on 2020-05-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0002_auto_20191220_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='materials_system.HashTag'),
            preserve_default=False,
        ),
    ]
