# Generated by Django 2.2.7 on 2020-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0002_auto_20200902_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації'),
        ),
    ]
