# Generated by Django 2.2.7 on 2020-05-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0003_hashtag_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='materials_system.HashTag'),
        ),
    ]
