# Generated by Django 2.2.7 on 2019-12-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0004_auto_20191204_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
