# Generated by Django 2.2.7 on 2020-05-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0004_auto_20200501_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='parent',
            new_name='tag_parent',
        ),
    ]
