# Generated by Django 2.2.7 on 2019-12-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0005_auto_20191204_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materials_system.Post')),
            ],
        ),
    ]
