# Generated by Django 2.2.7 on 2019-12-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0006_scratchpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
