# Generated by Django 2.2.7 on 2020-05-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0006_auto_20200501_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='tag_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tag_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials_system.HashTag'),
        ),
    ]
