# Generated by Django 2.2.7 on 2019-12-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0007_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_to_read',
            field=models.CharField(default='10 хвилин', max_length=20),
            preserve_default=False,
        ),
    ]
