# Generated by Django 2.2.7 on 2020-05-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0008_auto_20200507_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
