# Generated by Django 2.2.7 on 2019-12-05 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0008_post_time_to_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Прочитаєте'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='post',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication',
            field=models.TextField(verbose_name='Текст публікації'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_to_read',
            field=models.CharField(max_length=20, verbose_name='Прочитаєте за'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='posts', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Кількість переглядів'),
        ),
    ]
