# Generated by Django 2.2.7 on 2020-05-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0008_auto_20200507_1212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posthashtag',
            unique_together={('post', 'tag')},
        ),
    ]
