# Generated by Django 2.2.7 on 2019-12-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0009_auto_20191205_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Програмування'), (2, 'Шкільна інформатика'), (3, 'Інформаційні технології'), (4, 'Scratch'), (5, 'Стаття')], default=5),
        ),
    ]
