# Generated by Django 2.2.7 on 2019-12-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0010_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='schoolpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='scratchpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='ItPost',
        ),
        migrations.DeleteModel(
            name='ProgrammingPost',
        ),
        migrations.DeleteModel(
            name='SchoolPost',
        ),
        migrations.DeleteModel(
            name='ScratchPost',
        ),
    ]
