# Generated by Django 2.2.7 on 2020-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0010_auto_20200513_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Короткий опис'),
        ),
    ]
