# Generated by Django 2.2.7 on 2020-05-14 08:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0012_auto_20200514_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication',
            field=tinymce.models.HTMLField(),
        ),
    ]
