# Generated by Django 2.2.7 on 2019-12-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0012_auto_20191207_1504'),
        ('materials_system', '0012_auto_20191209_0230'),
    ]

    operations = [
    ]
