# Generated by Django 2.2.7 on 2020-05-14 08:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0013_auto_20200514_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication',
            field=tinymce.models.HTMLField(verbose_name='Текст публікації'),
        ),
    ]
