# Generated by Django 2.2.7 on 2020-05-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0009_auto_20200508_1429'),
        ('materials_system', '0014_auto_20200514_1154'),
    ]

    operations = [
    ]
