# Generated by Django 2.2.7 on 2020-05-16 09:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0015_merge_20200514_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст публікації'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Заголовок'),
        ),
    ]
