# Generated by Django 2.2.7 on 2020-05-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0016_auto_20200516_1206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hashtag',
            unique_together={('tag_name', 'tag_parent')},
        ),
    ]
