# Generated by Django 2.2.7 on 2020-05-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0018_hashtag_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='test',
        ),
    ]
