# Generated by Django 2.2.7 on 2020-08-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0020_auto_20200728_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, verbose_name='Дата публікації'),
        ),
    ]
