# Generated by Django 2.2.7 on 2020-08-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0021_auto_20200806_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації'),
        ),
    ]
