# Generated by Django 2.2.7 on 2020-08-20 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials_system', '0022_auto_20200806_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, verbose_name='Дата публікації'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст комментаря')),
                ('post', models.ManyToManyField(to='materials_system.Post', verbose_name='Пост до якого написан комментар')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Автор комментара')),
            ],
        ),
    ]
