# Generated by Django 2.2.7 on 2020-08-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0025_auto_20200824_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата написання коментаря'),
        ),
    ]
