# Generated by Django 2.2.7 on 2020-08-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_system', '0027_auto_20200824_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
