# Generated by Django 2.2.7 on 2020-08-24 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials_system', '0028_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст комментаря')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата написання коментаря')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials_system.Post', verbose_name='Пост до якого написан комментар')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials_system.Comments', verbose_name='Вiдповiдь на')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментара')),
            ],
        ),
    ]
