# Generated by Django 2.2.7 on 2019-12-09 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrition', models.CharField(max_length=256, verbose_name='Опис критерія')),
                ('max_value', models.IntegerField(verbose_name='Максимальний бал')),
                ('step', models.FloatField(verbose_name='Крок оцінки')),
            ],
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Дата почтку')),
                ('title', models.CharField(max_length=256, verbose_name='Назва олімпіади')),
                ('duration', models.DurationField(verbose_name='Час проведення')),
                ('description', models.TextField(verbose_name='Опис олімпіади')),
                ('olymp_type', models.PositiveSmallIntegerField(choices=[(1, 'Відкрита'), (2, 'За запрошенням')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Опис задачі')),
                ('files', models.FileField(blank=True, upload_to='', verbose_name='Додаткові матеріали')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiad_system.Olympiad', verbose_name='Олімпіада')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCriterias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiad_system.Criteria', verbose_name='Критерій')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiad_system.Task', verbose_name='Задача')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_file', models.FileField(upload_to='', verbose_name="Файл розв'язок")),
                ('reviewer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiad_system.Task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
            ],
        ),
    ]
