# Generated by Django 2.2.7 on 2019-12-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Excel'), (2, 'Access'), (3, 'Word'), (4, 'PowerPoint'), (5, 'Інше')], default=5, verbose_name='Розділ задачі'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Назва задачі'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olymp_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Відкрита'), (2, 'За запрошенням')], default=1, verbose_name='Тип проведення'),
        ),
    ]
