# Generated by Django 2.2.7 on 2020-12-15 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olympiad_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiad_system.Task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Відправник'),
        ),
        migrations.AddField(
            model_name='review',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiad_system.Criteria', verbose_name='Критерій'),
        ),
        migrations.AddField(
            model_name='review',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiad_system.Solution', verbose_name="Розв'язок"),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Зареєстровані для участі'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to=settings.AUTH_USER_MODEL, verbose_name='Члени жюрі'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiad_system.Task', verbose_name='Задача'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('solution', 'criteria')},
        ),
    ]
