# Generated by Django 2.2.7 on 2019-12-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad_system', '0002_auto_20191209_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='olympiad_system.Task', verbose_name='Задача'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskCriterias',
        ),
    ]
