# Generated by Django 2.2.7 on 2019-12-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad_system', '0002_auto_20191220_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='Завершена олімпіада'),
        ),
    ]
