# Generated by Django 2.2.7 on 2019-12-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad_system', '0003_olympiad_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='legend',
            field=models.CharField(blank=True, max_length=256, verbose_name='Легенда до задачі'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Умова задачі'),
        ),
    ]
