# Generated by Django 2.2.7 on 2019-12-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad_system', '0004_auto_20191220_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_alias',
            field=models.CharField(default='A', max_length=15, verbose_name='Id задачі'),
            preserve_default=False,
        ),
    ]
