# Generated by Django 2.2.7 on 2019-12-20 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad_system', '0007_auto_20191220_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
