# Generated by Django 2.2.7 on 2019-12-20 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympiad_system', '0008_auto_20191220_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to=settings.AUTH_USER_MODEL, verbose_name='Члени жюрі'),
        ),
    ]
