# Generated by Django 2.2.7 on 2019-12-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad_system', '0009_olympiad_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='encrypted_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
