# Generated by Django 2.2.7 on 2019-12-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad_system', '0010_solution_encrypted_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Очікується перевірка'), (2, 'Відбувається перевірка'), (3, 'Перевірка завершена')], default=1, verbose_name='Розділ задачі'),
        ),
    ]
