# Generated by Django 2.2.7 on 2019-12-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad_system', '0012_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='result',
            field=models.FloatField(default=0),
        ),
    ]
