# Generated by Django 2.2.7 on 2019-12-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='stydy_class',
            field=models.IntegerField(blank=True, default=9, verbose_name='Клас навчанн'),
        ),
    ]
