# Generated by Django 2.2.7 on 2019-12-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='about',
            field=models.TextField(verbose_name='Про себе'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Ім'я"),
        ),
    ]
