# Generated by Django 2.2.7 on 2019-12-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191204_0510'),
        ('users', '0002_auto_20191204_1934'),
    ]

    operations = [
    ]
