# Generated by Django 2.2.7 on 2020-08-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_systemuser_stydy_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200, verbose_name='Назва ролi')),
                ('can_post', models.BooleanField(default=False, verbose_name='Може публiкувати статтi')),
                ('can_edit_posts', models.BooleanField(default=False, verbose_name='Може редагувати чужi статтi')),
                ('can_change_hashtags', models.BooleanField(default=False, verbose_name='Можливicть редагувати та додавати хештеги')),
                ('can_edit_users', models.BooleanField(default=False, verbose_name='Можливicть редагування користувачiв')),
            ],
        ),
    ]
