# Generated by Django 2.2.7 on 2019-12-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20191204_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Ваше фото'),
        ),
    ]
