# Generated by Django 2.2.7 on 2019-12-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_systemuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.png', upload_to='avatars/', verbose_name='Ваше фото'),
        ),
    ]
