# Generated by Django 2.2.7 on 2019-12-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191209_0230'),
        ('users', '0005_auto_20191207_1504'),
    ]

    operations = [
    ]
