# Generated by Django 2.2.7 on 2020-08-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200803_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='role',
        ),
    ]
