# Generated by Django 2.2.7 on 2020-08-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_systemuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='role',
        ),
    ]
