# Generated by Django 2.2.7 on 2020-08-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_systemuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Role'),
        ),
    ]
