# Generated by Django 2.2.7 on 2020-08-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_systemuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
