# Generated by Django 2.2.7 on 2020-08-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200826_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='google_avatar',
            field=models.CharField(default='', max_length=250, verbose_name='Google avatar'),
        ),
    ]
